version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
       - DEBUG=True
       - VIDEO_SDK_TOKEN
       - VIDEO_SDK_CALL_WEBHOOK
       - REDIS_URL
       - VIDEO_SDK_CALL_DURATION_LIMIT
       - VIDEO_SDK_PUBLIC_KEY
       - EMAIL_FROM
       - SENDGRID_API_KEY
       - SENDGRID_TEMPLATE_ID_PASSWORD_RESET_OTP
       - ALLOWED_HOSTS
       - CORS_ALLOWED_ORIGINS
