version: '3.8'

services:
  server:
    build:
      context: ".."
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    network_mode: service:redis
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
