name: CI Backend

on:
  push:
    branches:
      - Setup-CI-pipeline-for-docker-github-actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/anambra-telemed-backend:latest
          build-args: |
            REDIS_URL=${{ secrets.REDIS_URL }}
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
            VIDEO_SDK_CALL_WEBHOOK=${{ secrets.VIDEO_SDK_CALL_WEBHOOK }}
            VIDEO_SDK_PUBLIC_KEY=${{ secrets.VIDEO_SDK_PUBLIC_KEY }}
            VIDEO_SDK_TOKEN=${{ secrets.VIDEO_SDK_TOKEN }}