name: CI Backend

on:
  push:
    branches:
      - Setup-CI-pipeline-for-docker-github-actions

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/anambra-telemed-backend:latest
          build-args: |
            REDIS_URL=${{ secrets.REDIS_URL }}
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
            VIDEO_SDK_CALL_WEBHOOK=${{ secrets.VIDEO_SDK_CALL_WEBHOOK }}
            VIDEO_SDK_PUBLIC_KEY=${{ secrets.VIDEO_SDK_PUBLIC_KEY }}
            VIDEO_SDK_TOKEN=${{ secrets.VIDEO_SDK_TOKEN }}

  deploy-image:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Set up SSH Agent and add private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy the Docker image on the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_ADDRESS }} << 'EOF'
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/anambra-telemed-backend:latest
            
            # Stop and remove any existing container running on port 8080
            docker stop anambra-backend || true
            docker rm anambra-backend || true

            # Run the new container on port 8080
            docker run -d -p 8080:8000 --name anambra-backend ${{ secrets.DOCKER_USERNAME }}/anambra-telemed-backend:latest
          EOF
