name: Build Backend Image

on:
  push:
    branches:
      - main
    tags:
      - '!*'
    # paths:
    #   - "backend/**"

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: telemedbackend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/anambra-telemed-backend:latest
          build-args: |
            EMAIL_FROM=${{ vars.EMAIL_FROM }}
            ALLOWED_HOSTS=${{ vars.ALLOWED_HOSTS }}
            ALLOWED_ORIGINS=${{ vars.ALLOWED_ORIGINS }}
            REDIS_URL=${{ vars.REDIS_URL }}
            SENDGRID_API_KEY=${{ vars.SENDGRID_API_KEY }}
            SENDGRID_TEMPLATE_ID_PASSWORD_RESET_OTP=${{ vars.SENDGRID_TEMPLATE_ID_PASSWORD_RESET_OTP }}
            VIDEO_SDK_CALL_WEBHOOK=${{ vars.VIDEO_SDK_CALL_WEBHOOK }}
            VIDEO_SDK_CALL_DURATION_LIMIT=${{ vars.VIDEO_SDK_CALL_DURATION_LIMIT }}

            VIDEO_SDK_TOKEN=${{ secrets.VIDEO_SDK_TOKEN }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            VIDEO_SDK_PUBLIC_KEY=${{ secrets.VIDEO_SDK_PUBLIC_KEY }}