name: Build and Deploy

on:
  push:
    branches:
      - Setup-CI-pipeline-for-docker-github-actions

jobs:
  build-images:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./frontend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build doctor-app
      env:
        VITE_VIDEO_SDK_TOKEN: ${{ secrets.VITE_VIDEO_SDK_TOKEN }}
        VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        VITE_WEBSOCKET_BASE: ${{ secrets.VITE_WEBSOCKET_BASE }}
      run: |
        npm run build:doctor

    - name: Build personnel-app
      env:
        VITE_VIDEO_SDK_TOKEN: ${{ secrets.VITE_VIDEO_SDK_TOKEN }}
        VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        VITE_WEBSOCKET_BASE: ${{ secrets.VITE_WEBSOCKET_BASE }}
      run: |
        npm run build:personnel

    - name: Build Docker image for doctor-app
      run: |
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/doctor-app:latest \
          -f apps/doctor-app/Dockerfile .

    - name: Build Docker image for personnel-app
      run: |
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/personnel-app:latest \
          -f apps/personnel-app/Dockerfile .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image for doctor-app
      run: docker push ${{ secrets.DOCKER_USERNAME }}/doctor-app:latest

    - name: Push Docker image for personnel-app
      run: docker push ${{ secrets.DOCKER_USERNAME }}/personnel-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Set up SSH Agent and add private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy doctor-app and personnel-app on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_ADDRESS }} << 'EOF'
            # Pull the latest images from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/doctor-app:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/personnel-app:latest
            
            # Stop and remove any existing containers
            docker stop doctor-app || true
            docker rm doctor-app || true
            docker stop personnel-app || true
            docker rm personnel-app || true

            # Run doctor-app on port 8081
            docker run -d -p 8081:80 --name doctor-app ${{ secrets.DOCKER_USERNAME }}/doctor-app:latest

            # Run personnel-app on port 8082
            docker run -d -p 8082:80 --name personnel-app ${{ secrets.DOCKER_USERNAME }}/personnel-app:latest
          EOF
