name: Build and Deploy

on:
  push:
    branches:
      - Setup-CI-pipeline-for-docker-github-actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./frontend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build doctor-app
      env:
        VITE_VIDEO_SDK_TOKEN: ${{ secrets.VITE_VIDEO_SDK_TOKEN }}
        VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        VITE_WEBSOCKET_BASE: ${{ secrets.VITE_WEBSOCKET_BASE }}
      run: |
        npx nx build doctor-app --prod

    - name: Build personnel-app
      env:
        VITE_VIDEO_SDK_TOKEN: ${{ secrets.VITE_VIDEO_SDK_TOKEN }}
        VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        VITE_WEBSOCKET_BASE: ${{ secrets.VITE_WEBSOCKET_BASE }}
      run: |
        npx nx build personnel-app --prod

    - name: Build Docker image for doctor-app
      run: |
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/doctor-app:latest \
          -f apps/doctor-app/Dockerfile .

    - name: Build Docker image for personnel-app
      run: |
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/personnel-app:latest \
          -f apps/personnel-app/Dockerfile .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image for doctor-app
      run: docker push ${{ secrets.DOCKER_USERNAME }}/doctor-app:latest

    - name: Push Docker image for personnel-app
      run: docker push ${{ secrets.DOCKER_USERNAME }}/personnel-app:latest
